### ISSUE TITLE
absolute reference to base & builder images

### ISSUE THREAD

**Issue by cirocosta** [cirocosta/monero-builds#3]
currently, dockerfiles in this repo start as such

https://github.com/cirocosta/monero-builds/blob/b2718db599303df081f74b19b565cd3c7f5abb8c/monero/Dockerfile#L11-L20

that has served us well so far, but, I believe that those references should **not** be pointing at tags (like, `debian:bullseye`), but instead, absolute references like `index.docker.io/library/debian@sha256:08db48d59c0a91afb802ebafc921be3154e200c452e4d0b19634b426b03e0e25`)

I think we can achieve that by making use of the same approach used for `MONERO_REVISION` where we have a `values.yaml` that describes the args in a map, which a tool like [gyr](https://github.com/cirocosta/gyr) can run over and replace these """relative""" references to absolute ones

e.g., we could do something like

```diff
  images:
    - type: monero
      image: utxobr/monero
      tags:
        - master
      args:
        MONERO_REPOSITORY: https://github.com/monero-project/monero
        MONERO_REVISION: gyr+gh://monero-project/monero#master
+       DEBIAN_IMAGE: gyr+docker://debian:bullseye
+       RUNTIME_IMAGE: gyr+docker://gcr.io/distroless/base-debian11:nonroot
      description: |-
        whatever latest commit is there on monero's `master` branch.
```

which, after a pass of `gyr`, would then get converted to 

```yaml
images:
  - type: monero
    image: utxobr/monero
    tags:
      - master
    args:
      MONERO_REPOSITORY: https://github.com/monero-project/monero
      MONERO_REVISION: 8fde011dbeb56ab92a909710567b964186671247
      DEBIAN_IMAGE: index.docker.io/library/debian@sha256:08db48d59c0a91afb802ebafc921be3154e200c452e4d0b19634b426b03e0e25
      RUNTIME_IMAGE: gcr.io/distroless/base-debian11@sha256:3e771f1b48c01332df37547182f9f2327c00567aa8204137f1832f3c42ce88f2
    description: |-
      whatever latest commit is there on monero's `master` branch.
```
